# Seed data for podologia (nail/foot specialty)
# Matches the legacy hardcoded fields from apps.clients.models.Client
# Used by: python manage.py seed_anamnesis --professional-email=<email>

SECTORS = [
    {
        'sector': 'Histórico',
        'sector_order': 0,
        'fields': [
            {
                'code': 'sport_activity',
                'label': 'Atividade esportiva',
                'field_type': 'radio',
                'options': ['Sim', 'Não', 'Às vezes'],
                'order': 0,
            },
            {
                'code': 'academic_activity',
                'label': 'Atividade acadêmica',
                'field_type': 'radio',
                'options': ['Sim', 'Não'],
                'order': 1,
            },
            {
                'code': 'takes_medication',
                'label': 'Toma medicação',
                'field_type': 'radio',
                'options': ['Sim', 'Não'],
                'order': 2,
            },
            {
                'code': 'takes_medication_details',
                'label': 'Qual medicação?',
                'field_type': 'text',
                'options': None,
                'order': 3,
                'placeholder': 'Informe a medicação...',
                'depends_on': 'takes_medication',
                'show_when_value': 'Sim',
            },
            {
                'code': 'had_surgery',
                'label': 'Já fez cirurgia',
                'field_type': 'radio',
                'options': ['Sim', 'Não'],
                'order': 4,
            },
            {
                'code': 'had_surgery_details',
                'label': 'Qual cirurgia?',
                'field_type': 'text',
                'options': None,
                'order': 5,
                'placeholder': 'Informe a cirurgia...',
                'depends_on': 'had_surgery',
                'show_when_value': 'Sim',
            },
            {
                'code': 'is_pregnant',
                'label': 'Está grávida',
                'field_type': 'radio',
                'options': ['Sim', 'Não'],
                'order': 6,
            },
            {
                'code': 'pain_sensitivity',
                'label': 'Sensibilidade à dor',
                'field_type': 'radio',
                'options': ['Baixa', 'Normal', 'Alta'],
                'order': 7,
            },
            {
                'code': 'clinical_history',
                'label': 'Histórico clínico',
                'field_type': 'textarea',
                'options': None,
                'order': 8,
            },
        ],
    },
    {
        'sector': 'Calçados',
        'sector_order': 1,
        'fields': [
            {
                'code': 'footwear_used',
                'label': 'Calçados que mais usa',
                'field_type': 'radio',
                'selection_mode': 'multiple',
                'options': ['Tênis', 'Chinelo', 'Salto alto', 'Outros'],
                'order': 0,
            },
            {
                'code': 'sock_used',
                'label': 'Meia utilizada',
                'field_type': 'radio',
                'options': ['Sim', 'Não', 'Às vezes'],
                'order': 1,
            },
        ],
    },
    {
        'sector': 'Pé Direito',
        'sector_order': 2,
        'fields': [
            {
                'code': 'plantar_view_right',
                'label': 'Vista plantar direita',
                'field_type': 'radio',
                'options': ['Normal', 'Plano', 'Cavo'],
                'order': 0,
            },
            {
                'code': 'dermatological_pathologies_right',
                'label': 'Patologias dermatológicas direito',
                'field_type': 'radio',
                'options': ['Ausente', 'Calosidade', 'Fissura', 'Verruga', 'Micose', 'Outro'],
                'order': 1,
            },
            {
                'code': 'nail_changes_right',
                'label': 'Alterações ungueais direito',
                'field_type': 'radio',
                'options': ['Ausente', 'Onicogrifose', 'Onicomicose', 'Unha encravada', 'Outro'],
                'order': 2,
            },
            {
                'code': 'deformities_right',
                'label': 'Deformidades direito',
                'field_type': 'radio',
                'options': ['Ausente', 'Hallux Valgus', 'Dedo em martelo', 'Dedo em garra', 'Outro'],
                'order': 3,
            },
            {
                'code': 'sensitivity_test',
                'label': 'Teste de sensibilidade direito',
                'field_type': 'radio',
                'options': ['Normal', 'Diminuído', 'Ausente'],
                'order': 4,
            },
        ],
    },
    {
        'sector': 'Pé Esquerdo',
        'sector_order': 3,
        'fields': [
            {
                'code': 'plantar_view_left',
                'label': 'Vista plantar esquerda',
                'field_type': 'radio',
                'options': ['Normal', 'Plano', 'Cavo'],
                'order': 0,
            },
            {
                'code': 'dermatological_pathologies_left',
                'label': 'Patologias dermatológicas esquerdo',
                'field_type': 'radio',
                'options': ['Ausente', 'Calosidade', 'Fissura', 'Verruga', 'Micose', 'Outro'],
                'order': 1,
            },
            {
                'code': 'nail_changes_left',
                'label': 'Alterações ungueais esquerdo',
                'field_type': 'radio',
                'options': ['Ausente', 'Onicogrifose', 'Onicomicose', 'Unha encravada', 'Outro'],
                'order': 2,
            },
            {
                'code': 'deformities_left',
                'label': 'Deformidades esquerdo',
                'field_type': 'radio',
                'options': ['Ausente', 'Hallux Valgus', 'Dedo em martelo', 'Dedo em garra', 'Outro'],
                'order': 3,
            },
            {
                'label': 'Teste de sensibilidade esquerdo',
                'field_type': 'radio',
                'options': ['Normal', 'Diminuído', 'Ausente'],
                'order': 4,
            },
        ],
    },
    {
        'sector': 'Observações',
        'sector_order': 4,
        'fields': [
            {
                'code': 'other_procedures',
                'label': 'Outros procedimentos',
                'field_type': 'textarea',
                'options': None,
                'order': 0,
            },
        ],
    },
]
