# Generated by Django 5.2.4 on 2026-09-05 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfessionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='Insira o token privado do seu Bot do Telegram caso queira usar um bot próprio.', max_length=120, null=True, verbose_name='Token do Bot (BotFather)')),
                ('chat_id', models.CharField(help_text='Identificador numérico do chat privado ou grupo para onde os alertas serão enviados.', max_length=64, verbose_name='ID do Chat / Canal')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Username no Telegram (@)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vínculo Ativo?')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Vinculado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_error', models.TextField(blank=True, verbose_name='Último Erro de Conexão/Envio')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant', verbose_name='Clínica/Tenant')),
            ],
            options={
                'verbose_name': 'Vínculo Telegram',
                'verbose_name_plural': 'Vínculos Telegram',
                'db_table': 'clinic_telegramprofessionallink',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'chat_id'), name='uniq_telegram_link_tenant_chat')],
            },
        ),
    ]
