# Generated by Django 5.2.4 on 2026-08-13 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de aprovacao'), ('APROVADO', 'Aprovado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=10)),
                ('customer_type', models.CharField(choices=[('PF', 'Pessoa fisica'), ('PJ', 'Pessoa juridica')], default='PJ', max_length=2)),
                ('nickname', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF must contain 11 digits.')])),
                ('cnpj', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ must contain 14 digits.')])),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Phone must contain 10 or 11 digits.')])),
                ('zip_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'ZIP code must contain 8 digits.')])),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bakery_customers', to=settings.AUTH_USER_MODEL)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_bakery_customers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_customers', to='authentication.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='BakeryCustomerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Cliente aprovado'), ('BLOCKED', 'Cliente bloqueado'), ('CREDIT_LIMIT_UPDATED', 'Limite atualizado'), ('UNBLOCKED', 'Cliente desbloqueado')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakery_customer_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='bakery.bakerycustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_customer_audit_logs', to='authentication.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('delivery_date', models.DateTimeField()),
                ('shipping_zip_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'ZIP code must contain 8 digits.')])),
                ('shipping_street', models.CharField(max_length=150)),
                ('shipping_number', models.CharField(max_length=20)),
                ('shipping_complement', models.CharField(blank=True, max_length=100)),
                ('shipping_neighborhood', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=2)),
                ('payment_method', models.CharField(choices=[('CREDIT', 'Fiado'), ('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('TRANSFER', 'Transferencia')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='bakery.bakerycustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_orders', to='authentication.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credito/Deposito'), ('DEBIT', 'Debito/Venda')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('reference_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger_entries', to='bakery.bakerycustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_credit_ledger_entries', to='authentication.tenant')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger_entries', to='bakery.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_products', to='authentication.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bakery.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakery_order_items', to='authentication.tenant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='bakery.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='bakerycustomer',
            index=models.Index(fields=['tenant', 'status'], name='bakery_bake_tenant__35515f_idx'),
        ),
        migrations.AddIndex(
            model_name='bakerycustomer',
            index=models.Index(fields=['tenant', 'nickname'], name='bakery_bake_tenant__3e444a_idx'),
        ),
        migrations.AddIndex(
            model_name='bakerycustomer',
            index=models.Index(fields=['created_at'], name='bakery_bake_created_0f5921_idx'),
        ),
        migrations.AddConstraint(
            model_name='bakerycustomer',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='uq_bakery_customer_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='bakerycustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('tenant', 'cpf'), name='uq_bakery_customer_tenant_cpf'),
        ),
        migrations.AddConstraint(
            model_name='bakerycustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('tenant', 'cnpj'), name='uq_bakery_customer_tenant_cnpj'),
        ),
        migrations.AddConstraint(
            model_name='bakerycustomer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', Decimal('0.00'))), name='ck_bakery_customer_credit_limit_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='bakerycustomerauditlog',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='bakery_bake_tenant__10abc2_idx'),
        ),
        migrations.AddIndex(
            model_name='bakerycustomerauditlog',
            index=models.Index(fields=['tenant', 'action', 'created_at'], name='bakery_bake_tenant__83f295_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='bakery_orde_tenant__71aed9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'created_at'], name='bakery_orde_tenant__bbfbab_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='bakery_cred_tenant__c28205_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['tenant', 'entry_type', 'created_at'], name='bakery_cred_tenant__2602aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='ck_bakery_ledger_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_key', ''), _negated=True), fields=('tenant', 'reference_key'), name='uq_bakery_ledger_tenant_reference_key'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='bakery_prod_tenant__65da86_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_bakery_product_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='ck_bakery_product_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'order'], name='bakery_orde_tenant__ab7882_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'order', 'product'), name='uq_bakery_order_item_tenant_order_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_bakery_order_item_quantity_positive'),
        ),
    ]
