# Generated by Django 5.2.4 on 2026-09-10 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_tenantmembership_role'),
        ('bakery', '0002_reconcile_paid_credit_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bakerycustomer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='uq_bakery_customer_tenant_phone'),
        ),
    ]
