# Generated by Django 5.2.4 on 2026-08-04 13:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=70, verbose_name='Sobrenome')),
                ('display_name', models.CharField(blank=True, help_text="Como os clientes a conhecem: ex. 'Podóloga Regiane', 'Dra. Juliana' ou 'Clínica Árcaro'. Se vazio, usa o primeiro nome.", max_length=100, verbose_name='Nome de exibição')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='BR', verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('register_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Registro Profissional')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('can_manage_professionals', models.BooleanField(default=False, verbose_name='Pode gerenciar profissionais')),
                ('totp_secret', models.CharField(blank=True, help_text='Base32 secret for TOTP (Google Authenticator). Empty = TOTP not configured.', max_length=64, verbose_name='TOTP Secret')),
                ('ui_theme', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('pink', 'Rosa'), ('black', 'Escuro')], default='blue', max_length=10, verbose_name='Tema da interface')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('deactivation_reason', models.CharField(blank=True, max_length=120, verbose_name='Motivo desativação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_hour', models.PositiveSmallIntegerField(default=6)),
                ('work_start_minute', models.PositiveSmallIntegerField(default=0)),
                ('work_end_hour', models.PositiveSmallIntegerField(default=21)),
                ('work_end_minute', models.PositiveSmallIntegerField(default=0)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=10)),
                ('default_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('default_visit_type', models.CharField(choices=[('consulta', 'Consulta'), ('avaliacao', 'Avaliação'), ('retorno', 'Retorno'), ('procedimento', 'Procedimento'), ('outro', 'Outro')], default='consulta', max_length=20)),
                ('confirm_message_enabled', models.BooleanField(default=False)),
                ('confirm_message_template', models.TextField(blank=True)),
                ('pix_key_type', models.CharField(blank=True, choices=[('telefone', 'Telefone'), ('cpf', 'CPF'), ('email', 'E-mail'), ('aleatoria', 'Aleatória')], default='', max_length=16)),
                ('pix_key_value', models.CharField(blank=True, default='', max_length=128)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_minutes_before', models.PositiveSmallIntegerField(default=90, help_text='Quantos minutos antes do compromisso enviar o lembrete Telegram.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Configuração do Profissional',
                'verbose_name_plural': 'Configurações de Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='authenticat_slug_1d16c5_idx'), models.Index(fields=['is_active'], name='authenticat_is_acti_988400_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial WebAuthn',
                'verbose_name_plural': 'Credenciais WebAuthn',
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=32)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['professional', 'is_active'], name='authenticat_profess_3af53c_idx'), models.Index(fields=['professional', 'device_id'], name='authenticat_profess_1991a3_idx')],
                'unique_together': {('professional', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.tenant')),
            ],
            options={
                'verbose_name': 'Tenant membership',
                'verbose_name_plural': 'Tenant memberships',
                'indexes': [models.Index(fields=['professional', 'is_active'], name='authenticat_profess_c34cb6_idx'), models.Index(fields=['tenant', 'role'], name='authenticat_tenant__f4d3df_idx')],
                'unique_together': {('tenant', 'professional')},
            },
        ),
    ]
