# Generated by Django 5.2.4 on 2026-09-05 13:00

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=70, verbose_name='Sobrenome')),
                ('display_name', models.CharField(blank=True, help_text="Como os clientes o conhecem visualmente nas notificações: ex. 'Podóloga Regiane'.", max_length=100, verbose_name='Nome de exibição')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='BR', verbose_name='Telefone Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail corporativo')),
                ('register_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Registro Profissional (CRM/CRBM)')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidade Atendida')),
                ('can_manage_professionals', models.BooleanField(default=False, verbose_name='Pode gerenciar profissionais / Admin global')),
                ('totp_secret', models.CharField(blank=True, help_text='Chave Base32 para Google Authenticator. Se vazio, o 2FA local fica totalmente desativado.', max_length=64, verbose_name='Segredo TOTP (2FA)')),
                ('ui_theme', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('pink', 'Rosa')], default='blue', max_length=10, verbose_name='Tema visual do Painel')),
                ('lock_odonto_plan_after_print', models.BooleanField(default=True, help_text='Quando ativo, a impressão de um plano odontológico bloqueia novas edições.', verbose_name='Bloquear plano odontológico após impressão')),
                ('odonto_quote_validity_days', models.PositiveSmallIntegerField(default=30, help_text='Prazo exibido nos orçamentos odontológicos impressos.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Validade do orçamento odontológico (dias)')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('address', models.CharField(blank=True, max_length=160, verbose_name='Endereço comercial')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=80, verbose_name='Bairro')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Django Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário Ativo no Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('deactivation_reason', models.CharField(blank=True, max_length=120, verbose_name='Motivo do Desligamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_hour', models.PositiveSmallIntegerField(default=6, verbose_name='Hora de Início da Agenda')),
                ('work_start_minute', models.PositiveSmallIntegerField(default=0)),
                ('work_end_hour', models.PositiveSmallIntegerField(default=21, verbose_name='Hora de Término da Agenda')),
                ('work_end_minute', models.PositiveSmallIntegerField(default=0)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='Intervalo de Grade (Minutos)')),
                ('default_duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Duração Sugerida de Atendimento')),
                ('default_visit_type', models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('outro', 'Outro compromisso')], default='consulta', max_length=20, verbose_name='Tipo Sugerido de Atendimento')),
                ('confirm_message_enabled', models.BooleanField(default=False, verbose_name='Disparar confirmações automáticas?')),
                ('confirm_message_template', models.TextField(blank=True, verbose_name='Template da Mensagem de Alerta')),
                ('pix_key_type', models.CharField(blank=True, choices=[('telefone', 'Telefone'), ('cpf', 'CPF'), ('email', 'E-mail'), ('aleatoria', 'Chave Aleatória')], default='', max_length=16)),
                ('pix_key_value', models.CharField(blank=True, default='', max_length=128)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_minutes_before', models.PositiveSmallIntegerField(default=90, help_text='Quantos minutos antes do compromisso enviar o lembrete Telegram.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Configuração do Profissional',
                'verbose_name_plural': 'Configurações de Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome da Empresa / Unidade')),
                ('slug', models.SlugField(help_text="Texto amigável usado na URL para identificar a clínica. Ex: 'clinica-arcaro'", max_length=140, unique=True, verbose_name='Identificador na URL (Slug)')),
                ('ecosystem', models.CharField(choices=[('clinic', 'Unidade Clínica (Saúde/Estética)'), ('bakery', 'Unidade Padaria (Alimentação/Varejo)')], default='clinic', max_length=20, verbose_name='Ecossistema / Tipo de Negócio')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='Capacidades / Funcionalidades Ativas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cadastro Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa (Tenant)',
                'verbose_name_plural': 'Empresas (Tenants)',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='authenticat_slug_1d16c5_idx'), models.Index(fields=['is_active'], name='authenticat_is_acti_988400_idx'), models.Index(fields=['ecosystem', 'is_active'], name='authenticat_ecosyst_61a29c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(help_text='ID retornado pelo navegador.', unique=True)),
                ('public_key', models.TextField(help_text='Chave pública codificada em base64.')),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('device_name', models.CharField(blank=True, max_length=120, verbose_name='Nome do Aparelho (ex: iPhone de Eduardo)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Profissional Vinculado')),
            ],
            options={
                'verbose_name': 'Credencial WebAuthn',
                'verbose_name_plural': 'Credenciais WebAuthn',
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, verbose_name='Identificador Único do Aparelho')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Navegador / App')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sessão Válida?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=32)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria - Sessão de Dispositivo',
                'verbose_name_plural': 'Auditoria - Sessões de Dispositivos',
                'indexes': [models.Index(fields=['professional', 'is_active'], name='authenticat_profess_3af53c_idx'), models.Index(fields=['professional', 'device_id'], name='authenticat_profess_1991a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('professional', 'device_id'), name='uniq_professional_device_session')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário / Sócio Diretor'), ('admin', 'Administrador da Unidade'), ('member', 'Membro Operacional / Profissional de Saúde')], default='member', max_length=20, verbose_name='Nível de Permissão (Role)')),
                ('login_alias', models.CharField(blank=True, default='', help_text='Permite ao profissional autenticar-se usando um apelido curto em vez do e-mail.', max_length=60, verbose_name='Apelido de Login Rápido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vínculo Habilitado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Profissional Vinculado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.tenant', verbose_name='Empresa / Clínica')),
            ],
            options={
                'verbose_name': 'Vínculo de Acesso (Membership)',
                'verbose_name_plural': 'Vínculos de Acessos (Memberships)',
                'indexes': [models.Index(fields=['professional', 'is_active'], name='authenticat_profess_c34cb6_idx'), models.Index(fields=['tenant', 'role'], name='authenticat_tenant__f4d3df_idx'), models.Index(fields=['tenant', 'login_alias'], name='authenticat_tenant__5f2d87_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'professional'), name='uniq_tenant_membership_professional_combination'), models.UniqueConstraint(condition=models.Q(('login_alias__gt', '')), fields=('tenant', 'login_alias'), name='uq_tenant_membership_login_alias')],
            },
        ),
    ]
