# Generated by Django 5.2.4 on 2026-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='address',
            field=models.CharField(blank=True, max_length=160, verbose_name='Endereço comercial'),
        ),
        migrations.AddField(
            model_name='professional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='professional',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=80, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='professional',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='professional',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
