# Generated by Django 5.2.4 on 2026-08-23 23:07

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='odonto_quote_validity_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Prazo exibido nos orçamentos odontológicos impressos.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Validade do orçamento odontológico (dias)'),
        ),
    ]
