# Generated by Django 5.2.4 on 2026-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ecosystem',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('bakery', 'Bakery')], default='clinic', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='login_alias',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['ecosystem', 'is_active'], name='authenticat_ecosyst_61a29c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'login_alias'], name='authenticat_tenant__5f2d87_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('login_alias__gt', '')), fields=('tenant', 'login_alias'), name='uq_tenant_membership_login_alias'),
        ),
    ]
