# Generated by Django 5.2.4 on 2026-10-03 22:03

import django.db.models.functions.text
from django.db import migrations, models


def normalize_login_aliases(apps, schema_editor):
    TenantMembership = apps.get_model('authentication', 'TenantMembership')
    seen = {}
    updates = []

    memberships = TenantMembership.objects.exclude(login_alias='').only(
        'id', 'tenant_id', 'login_alias'
    )
    for membership in memberships.iterator():
        normalized = membership.login_alias.strip().lower()
        key = (membership.tenant_id, normalized)
        previous_id = seen.get(key)
        if previous_id is not None and previous_id != membership.id:
            raise RuntimeError(
                'Conflito de login_alias após normalização no tenant '
                f'{membership.tenant_id}: {normalized}'
            )
        seen[key] = membership.id
        if normalized != membership.login_alias:
            updates.append((membership.id, normalized))

    for membership_id, normalized in updates:
        TenantMembership.objects.filter(pk=membership_id).update(
            login_alias=normalized
        )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_login_aliases, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='tenantmembership',
            name='uq_tenant_membership_login_alias',
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(models.F('tenant'), django.db.models.functions.text.Lower('login_alias'), condition=models.Q(('login_alias__gt', '')), name='uq_tenant_membership_login_alias_ci'),
        ),
    ]
