# Generated by Django 5.2.4 on 2026-09-05 13:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Obrigatório para ativação e recebimento de notificações via Telegram. Ex: (19) 99876-5432 ou 19998765432.', max_length=128, region='BR', verbose_name='Telefone Celular'),
        ),
    ]
