# Generated by Django 5.2.4 on 2026-09-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_professional_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="totp_secret",
        ),
    ]