# Generated by Django 5.2.4 on 2026-10-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_tenantmembership_uq_tenant_membership_login_alias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceSession',
        ),
    ]
