# Generated by Django 5.2.4 on 2026-09-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_professional_totp_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
