# Generated by Django 5.2.4 on 2026-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_devicesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='ecosystem',
            field=models.CharField(choices=[('clinic', 'Unidade Clínica (Saúde/Estética)'), ('bakery', 'Unidade Padaria (Alimentação/Varejo)')], max_length=20, verbose_name='Ecossistema / Tipo de Negócio'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('ecosystem', ''), _negated=True), name='tenant_ecosystem_not_empty'),
        ),
    ]
