# Generated by Django 5.2.4 on 2026-10-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_alter_tenant_ecosystem_and_more'),
        ('bakery', '0001_initial'),
        ('clinic', '0001_initial'),
        ('notifications', '0002_telegram_link_per_tenant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professional',
            new_name='SystemUser',
        ),
    ]
