# Generated by Django 5.2.4 on 2026-09-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_webauthncredential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionalsettings",
            name="pix_key_type",
        ),
        migrations.RemoveField(
            model_name="professionalsettings",
            name="pix_key_value",
        ),
    ]