# Generated by Django 5.2.4 on 2026-09-07 21:27

from django.db import migrations, models


def copy_tenant_names_to_trade_names(apps, schema_editor):
    Tenant = apps.get_model("authentication", "Tenant")
    Tenant.objects.filter(trade_name="").update(trade_name=models.F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_professionalsettings_pix_key_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='trade_name',
            field=models.CharField(blank=True, default='', help_text='Nome público exibido nos painéis, documentos e comunicações.', max_length=120, verbose_name='Nome Fantasia'),
        ),
        migrations.RunPython(copy_tenant_names_to_trade_names, migrations.RunPython.noop),
    ]
