# Generated by Django 5.2.4 on 2026-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_tenant_trade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='trade_name',
            field=models.CharField(help_text='Nome público exibido nos painéis, documentos e comunicações.', max_length=120, verbose_name='Nome Fantasia'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('trade_name', ''), _negated=True), name='tenant_trade_name_not_empty'),
        ),
    ]
