# Generated by Django 5.2.4 on 2026-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_tenant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono da Empresa'), ('admin', 'Administrador da Unidade'), ('member', 'Membro / Profissional de Saúde')], default='member', max_length=20, verbose_name='Nível de Permissão (Role)'),
        ),
    ]
