import csv
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):
    help = 'Promote high-confidence assisted reconciliation suggestions into approved aliases and review queues.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--input',
            type=str,
            default='info/migration/odonto_reconciliation_assisted_2026-04-28.csv',
            help='Input CSV generated by assist_bruna_reconciliation.',
        )
        parser.add_argument(
            '--output-approved',
            type=str,
            default='info/migration/odonto_reconciliation_approved_2026-04-28.csv',
            help='CSV path for semiautomatically approved aliases.',
        )
        parser.add_argument(
            '--output-review',
            type=str,
            default='info/migration/odonto_reconciliation_review_2026-04-28.csv',
            help='CSV path for manual review candidates.',
        )
        parser.add_argument(
            '--min-score',
            type=float,
            default=0.95,
            help='Minimum score for semiautomatic approval.',
        )
        parser.add_argument(
            '--min-gap',
            type=float,
            default=0.03,
            help='Minimum difference between top-1 and top-2 score for approval.',
        )

    def handle(self, *args, **options):
        input_path = self._resolve_path(options['input'])
        approved_path = self._resolve_path(options['output_approved'])
        review_path = self._resolve_path(options['output_review'])
        min_score = float(options['min_score'])
        min_gap = float(options['min_gap'])

        if not input_path.exists():
            raise CommandError(f'Input CSV not found: {input_path}')

        grouped = {}
        with open(input_path, 'r', encoding='utf-8', newline='') as f:
            reader = csv.DictReader(f)
            for row in reader:
                grouped.setdefault(row['legacy_name'], []).append(row)

        approved_rows = []
        review_rows = []

        for legacy_name, rows in sorted(grouped.items(), key=lambda kv: kv[0].lower()):
            candidate_rows = [r for r in rows if (r.get('candidate_client_id') or '').strip()]
            candidate_rows.sort(key=lambda r: int(r.get('candidate_rank') or 9999))

            top = candidate_rows[0] if candidate_rows else None
            second = candidate_rows[1] if len(candidate_rows) > 1 else None
            top_score = float(top['score']) if top and top.get('score') else 0.0
            second_score = float(second['score']) if second and second.get('score') else 0.0
            top_gap = top_score - second_score

            if top and top_score >= min_score and top_gap >= min_gap:
                approved_rows.append({
                    'legacy_name': top['legacy_name'],
                    'legacy_name_repaired': top['legacy_name_repaired'],
                    'client_id': top['candidate_client_id'],
                    'client_name': top['candidate_client_name'],
                    'score': top['score'],
                    'score_gap': f'{top_gap:.4f}',
                    'treatment_count': top['treatment_count'],
                })
                continue

            if candidate_rows:
                for row in candidate_rows:
                    review_rows.append({
                        'legacy_name': row['legacy_name'],
                        'legacy_name_repaired': row['legacy_name_repaired'],
                        'treatment_count': row['treatment_count'],
                        'candidate_rank': row['candidate_rank'],
                        'candidate_client_id': row['candidate_client_id'],
                        'candidate_client_name': row['candidate_client_name'],
                        'score': row['score'],
                        'top_score': f'{top_score:.4f}',
                        'score_gap_from_top1': f'{(top_score - float(row["score"])):.4f}',
                    })
            else:
                row = rows[0]
                review_rows.append({
                    'legacy_name': row['legacy_name'],
                    'legacy_name_repaired': row['legacy_name_repaired'],
                    'treatment_count': row['treatment_count'],
                    'candidate_rank': '',
                    'candidate_client_id': '',
                    'candidate_client_name': '',
                    'score': '',
                    'top_score': '',
                    'score_gap_from_top1': '',
                })

        self._write_csv(
            approved_path,
            approved_rows,
            [
                'legacy_name',
                'legacy_name_repaired',
                'client_id',
                'client_name',
                'score',
                'score_gap',
                'treatment_count',
            ],
        )
        self._write_csv(
            review_path,
            review_rows,
            [
                'legacy_name',
                'legacy_name_repaired',
                'treatment_count',
                'candidate_rank',
                'candidate_client_id',
                'candidate_client_name',
                'score',
                'top_score',
                'score_gap_from_top1',
            ],
        )

        self.stdout.write(self.style.SUCCESS('\n✅ Semiautomatic reconciliation files generated!'))
        self.stdout.write(f'  Approved aliases: {len(approved_rows)}')
        self.stdout.write(f'  Review rows: {len(review_rows)}')
        self.stdout.write(f'  Approved file: {approved_path}')
        self.stdout.write(f'  Review file: {review_path}')

    def _resolve_path(self, value):
        path = Path(value)
        if not path.is_absolute():
            path = Path.cwd() / path
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def _write_csv(self, path, rows, fieldnames):
        with open(path, 'w', encoding='utf-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
