# Generated by Django 5.2.4 on 2026-08-21 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_professional_address_professional_cnpj_and_more'),
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseOdontologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gum_bleeding', models.BooleanField(default=False, verbose_name='Gengiva sangra ao escovar?')),
                ('floss_usage', models.BooleanField(default=False, verbose_name='Usa fio dental diariamente?')),
                ('bruxism_clenching', models.BooleanField(default=False, verbose_name='Apresenta Bruxismo / Apertamento?')),
                ('tooth_brushing_frequency', models.CharField(blank=True, default='', max_length=30, verbose_name='Frequência de Escovação')),
                ('chief_dental_complaint', models.TextField(blank=True, default='', verbose_name='Queixa Principal Bucal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anamnese Especialidade - Odontologia',
                'verbose_name_plural': 'Anamneses Especialidade - Odontologia',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DentalProcedureContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('tooth', 'Dente Específico'), ('arch', 'Arcada Inteira'), ('full', 'Boca Toda')], default='tooth', max_length=10, verbose_name='Escopo Anatômico')),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, help_text='Notação FDI/ISO 3950: 11–48 permanentes, 51–85 decíduos.', null=True, verbose_name='Número FDI do Dente')),
                ('tooth_surface', models.CharField(blank=True, default='', help_text='Uma ou mais faces separadas por vírgula: O, M, D, V, L, I.', max_length=20, verbose_name='Face(s) Clínica(s)')),
                ('arcade_arch', models.CharField(blank=True, choices=[('superior', 'Arcada Superior'), ('inferior', 'Arcada Inferior')], max_length=10, null=True, verbose_name='Arcada')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observações do Dente')),
            ],
            options={
                'verbose_name': 'Contexto Anatômico Dentário',
                'verbose_name_plural': 'Contextos Anatômicos Dentários',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Nome do Plano')),
                ('status', models.CharField(choices=[('pending', 'Em Tratamento'), ('completed', 'Tratamento Concluído'), ('archived', 'Arquivado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('is_printed', models.BooleanField(default=False, help_text='Trava o plano contra edição/exclusão após a impressão do orçamento.', verbose_name='Impresso')),
                ('printed_at', models.DateTimeField(blank=True, help_text='Momento em que o orçamento foi confirmado como impresso e travado.', null=True, verbose_name='Data da impressão')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Anotações Gerais do Caso')),
                ('external_treatment_id', models.BigIntegerField(blank=True, help_text='ID_PT_HEADER importado do banco legado.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Tratamento Odontológico',
                'verbose_name_plural': 'Planos de Tratamento Odontológico',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'Procedimento / Serviço'), ('product', 'Insumo / Material Consumível')], default='service', max_length=10, verbose_name='Tipo de Item')),
                ('custom_name', models.CharField(blank=True, default='', help_text='Preenchido apenas quando não há serviço ou produto no catálogo.', max_length=255, verbose_name='Nome Personalizado')),
                ('status', models.CharField(choices=[('pending', 'Pendente (Orçado)'), ('completed', 'Concluído (Realizado)'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status de Execução')),
                ('patient_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Orçado ao Paciente (R$)')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas Clínicas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('external_item_id', models.BigIntegerField(blank=True, help_text='ID_PT_ITEM do banco legado.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item do Plano de Tratamento',
                'verbose_name_plural': 'Itens do Plano de Tratamento',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='dentalarcade',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dentalarcade',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='dentalarcade',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tooth',
            name='arcade',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='arcade',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='parent_procedure',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='tooth',
        ),
        migrations.RemoveField(
            model_name='procedurenamesuggestion',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='procedurenamesuggestion',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='productcatalogitem',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='productcatalogitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='tooth',
        ),
        migrations.RemoveField(
            model_name='tooth',
            name='tenant',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='clinic_appo_finaliz_d8b66e_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ended_device_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ended_device_info',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='finalized_at',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_notes',
            field=models.TextField(blank=True, default='', help_text='Observações reutilizadas ao lançar este serviço em um atendimento.', verbose_name='Observações Padrão do Atendimento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('done', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='anamneseodontologia',
            name='anamnese_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontologia', to='clinic.anamnesebase', verbose_name='Anamnese Base'),
        ),
        migrations.AddField(
            model_name='anamneseodontologia',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_odontologia', to=settings.AUTH_USER_MODEL, verbose_name='Dentista Responsável'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='clinic.client', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Dentista Responsável'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_items', to='clinic.treatmentplanitem', verbose_name='Item Pai (Procedimento)'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.treatmentplan', verbose_name='Plano de Tratamento'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_items', to='clinic.product', verbose_name='Produto do Catálogo'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_items', to='clinic.service', verbose_name='Serviço do Catálogo'),
        ),
        migrations.AddField(
            model_name='dentalprocedurecontext',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_context', to='clinic.treatmentplanitem', verbose_name='Item do Plano'),
        ),
        migrations.DeleteModel(
            name='DentalArcade',
        ),
        migrations.DeleteModel(
            name='FinalizeAudit',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='ProcedureNameSuggestion',
        ),
        migrations.DeleteModel(
            name='ProductCatalogItem',
        ),
        migrations.DeleteModel(
            name='Surface',
        ),
        migrations.DeleteModel(
            name='Tooth',
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['tenant', 'professional', 'client'], name='clinic_trea_tenant__4c600b_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['tenant', 'status'], name='clinic_trea_tenant__336e76_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentplan',
            constraint=models.UniqueConstraint(condition=models.Q(('external_treatment_id__isnull', False)), fields=('tenant', 'professional', 'external_treatment_id'), name='uniq_treatment_plan_migration_control'),
        ),
        migrations.AddConstraint(
            model_name='treatmentplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='treatment_plan_completed_requires_completed_at'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['plan', 'status'], name='clinic_trea_plan_id_377234_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['plan', 'kind'], name='clinic_trea_plan_id_87ae25_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentplanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_item_id__isnull', False)), fields=('plan', 'external_item_id'), name='uniq_treatment_item_migration_control'),
        ),
        migrations.AddConstraint(
            model_name='treatmentplanitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='treatment_item_completed_requires_completed_at'),
        ),
        migrations.AddIndex(
            model_name='dentalprocedurecontext',
            index=models.Index(fields=['item', 'scope'], name='clinic_dent_item_id_8f9939_idx'),
        ),
        migrations.AddIndex(
            model_name='dentalprocedurecontext',
            index=models.Index(fields=['tooth_number'], name='clinic_dent_tooth_n_b0f0ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='dentalprocedurecontext',
            constraint=models.CheckConstraint(condition=models.Q(('tooth_number__isnull', True), models.Q(('tooth_number__gte', 11), ('tooth_number__lte', 18)), models.Q(('tooth_number__gte', 21), ('tooth_number__lte', 28)), models.Q(('tooth_number__gte', 31), ('tooth_number__lte', 38)), models.Q(('tooth_number__gte', 41), ('tooth_number__lte', 48)), models.Q(('tooth_number__gte', 51), ('tooth_number__lte', 55)), models.Q(('tooth_number__gte', 61), ('tooth_number__lte', 65)), models.Q(('tooth_number__gte', 71), ('tooth_number__lte', 75)), models.Q(('tooth_number__gte', 81), ('tooth_number__lte', 85)), _connector='OR'), name='dental_context_valid_fdi_tooth_number'),
        ),
        migrations.AddConstraint(
            model_name='dentalprocedurecontext',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'tooth'), _negated=True), ('tooth_number__isnull', False), _connector='OR'), name='dental_context_tooth_scope_requires_number'),
        ),
        migrations.AddConstraint(
            model_name='dentalprocedurecontext',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'arch'), _negated=True), ('arcade_arch__isnull', False), _connector='OR'), name='dental_context_arch_scope_requires_arch'),
        ),
    ]
