# Generated by Django 5.2.4 on 2026-08-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseOdontologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gum_bleeding', models.BooleanField(default=False, verbose_name='Gengiva sangra ao escovar?')),
                ('floss_usage', models.BooleanField(default=False, verbose_name='Usa fio dental diariamente?')),
                ('bruxism_clenching', models.BooleanField(default=False, verbose_name='Apresenta Bruxismo / Apertamento?')),
                ('tooth_brushing_frequency', models.CharField(blank=True, default='', max_length=30, verbose_name='Frequência de Escovação')),
                ('chief_dental_complaint', models.TextField(blank=True, default='', verbose_name='Queixa Principal Bucal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anamnese_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontologia', to='clinic.anamnesebase', verbose_name='Anamnese Base')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_odontologia', to=settings.AUTH_USER_MODEL, verbose_name='Dentista Responsável')),
            ],
            options={
                'verbose_name': 'Anamnese Especialidade - Odontologia',
                'verbose_name_plural': 'Anamneses Especialidade - Odontologia',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
