# Generated by Django 5.2.4 on 2026-08-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_anamneseodontologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='finalizeaudit',
            name='tenant',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='clinic_appo_finaliz_d8b66e_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ended_device_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ended_device_info',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='finalized_at',
        ),
        migrations.DeleteModel(
            name='FinalizeAudit',
        ),
    ]
