# Generated by Django 5.2.4 on 2026-08-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_professional_odonto_quote_validity_days'),
        ('clinic', '0003_infer_legacy_service_treatment_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodologyProcedureContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('pe_esquerdo', 'Pé Esquerdo'), ('pe_direito', 'Pé Direito'), ('mao_esquerda', 'Mão Esquerda'), ('mao_direita', 'Mão Direita'), ('geral', 'Geral / Outros (Não Anatômico)')], default='geral', max_length=20, verbose_name='Escopo Anatômico')),
                ('location_number', models.IntegerField(blank=True, help_text='Número do dedo (1 a 5) ou região afetada no SVG do Frontend', null=True, verbose_name='Número da Localização / Dedo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant', verbose_name='Empresa/Inquilino')),
                ('treatment_plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podology_context', to='clinic.treatmentplanitem', verbose_name='Item do Plano de Tratamento')),
            ],
            options={
                'verbose_name': 'Contexto de Procedimento de Podologia',
                'verbose_name_plural': 'Contextos de Procedimento de Podologia',
                'db_table': 'clinic_podology_context',
            },
        ),
    ]
