# Generated by Django 5.2.4 on 2026-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_procedure_arcade_remove_tooth_arcade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_notes',
            field=models.TextField(blank=True, default='', help_text='Observações reutilizadas ao lançar este serviço em um atendimento.', verbose_name='Observações Padrão do Atendimento'),
        ),
    ]
