# Generated by Django 5.2.4 on 2026-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_service_default_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Em Tratamento'), ('completed', 'Tratamento Concluído'), ('archived', 'Arquivado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
