# Generated by Django 5.2.4 on 2026-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_treatmentplan_name_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='is_printed',
            field=models.BooleanField(default=False, help_text='Trava o plano contra edição/exclusão após a impressão do orçamento.', verbose_name='Impresso'),
        ),
    ]
