# Generated by Django 5.2.4 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_treatmentplan_is_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='printed_at',
            field=models.DateTimeField(blank=True, help_text='Momento em que o orçamento foi confirmado como impresso e travado.', null=True, verbose_name='Data da impressão'),
        ),
    ]
