# Generated by Django 5.2.4 on 2026-07-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='academic_activity',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clinical_history',
        ),
        migrations.RemoveField(
            model_name='client',
            name='deformities_left',
        ),
        migrations.RemoveField(
            model_name='client',
            name='deformities_right',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dermatological_pathologies_left',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dermatological_pathologies_right',
        ),
        migrations.RemoveField(
            model_name='client',
            name='footwear_used',
        ),
        migrations.RemoveField(
            model_name='client',
            name='had_surgery',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nail_changes_left',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nail_changes_right',
        ),
        migrations.RemoveField(
            model_name='client',
            name='other_procedures',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pain_sensitivity',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantar_view_left',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantar_view_right',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sensitivity_test',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sock_used',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sport_activity',
        ),
        migrations.RemoveField(
            model_name='client',
            name='takes_medication',
        ),
    ]
