# Generated by Django 5.2.4 on 2026-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0004_remove_anamnesis_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesisfield',
            name='selection_mode',
            field=models.CharField(choices=[('single', 'Seleção única'), ('multiple', 'Seleção múltipla')], default='single', help_text='Use multiple para campos de checklist com concatenação textual.', max_length=10, verbose_name='Modo de seleção'),
        ),
    ]
