# Generated by Django 5.2.4 on 2026-07-26 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0005_anamnesisfield_selection_mode'),
        ('clients', '0007_remove_client_academic_activity_and_more'),
        ('tenancy', '0002_backfill_existing_tenants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takes_medication', models.CharField(blank=True, max_length=255, null=True, verbose_name='Toma medicação')),
                ('had_surgery', models.CharField(blank=True, max_length=255, null=True, verbose_name='Já fez cirurgia')),
                ('is_pregnant', models.BooleanField(blank=True, null=True, verbose_name='Está grávida')),
                ('pain_sensitivity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sensibilidade à dor')),
                ('clinical_history', models.TextField(blank=True, null=True, verbose_name='Histórico clínico')),
                ('sport_activity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Atividade esportiva')),
                ('academic_activity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Atividade acadêmica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_base', to='clients.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_base', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_base', to='tenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Anamnese base',
                'verbose_name_plural': 'Anamneses base',
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'tenant', 'professional'), name='uniq_anamnese_base_client_tenant_professional')],
            },
        ),
        migrations.CreateModel(
            name='AnamnesePodologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwear_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calçado usado')),
                ('sock_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meia usada')),
                ('plantar_view_left', models.TextField(blank=True, null=True, verbose_name='Vista plantar esquerda')),
                ('plantar_view_right', models.TextField(blank=True, null=True, verbose_name='Vista plantar direita')),
                ('dermatological_pathologies_left', models.TextField(blank=True, null=True, verbose_name='Patologias pé esquerdo')),
                ('dermatological_pathologies_right', models.TextField(blank=True, null=True, verbose_name='Patologias pé direito')),
                ('nail_changes_left', models.TextField(blank=True, null=True, verbose_name='Alterações nas unhas pé esquerdo')),
                ('nail_changes_right', models.TextField(blank=True, null=True, verbose_name='Alterações nas unhas pé direito')),
                ('deformities_left', models.TextField(blank=True, null=True, verbose_name='Deformidades pé esquerdo')),
                ('deformities_right', models.TextField(blank=True, null=True, verbose_name='Deformidades pé direito')),
                ('sensitivity_test', models.TextField(blank=True, null=True, verbose_name='Teste de sensibilidade')),
                ('other_procedures', models.TextField(blank=True, null=True, verbose_name='Outros procedimentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_podologia', to='clients.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_podologia', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_podologia', to='tenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Anamnese podologia',
                'verbose_name_plural': 'Anamneses podologia',
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'tenant', 'professional'), name='uniq_anamnese_podologia_client_tenant_professional')],
            },
        ),
    ]
