# Generated by Django 5.2.4 on 2026-07-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0007_remove_procedure_odonto_proc_arcade_is_produc_idx_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalarcade',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='procedurenamesuggestion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='productcatalogitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='surface',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tooth',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
    ]
